// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjIvIZclStx-gFMk2LDx53WIbjh9i4EMI',
    appId: '1:60824383146:android:4cf08c69b658f91725ead3',
    messagingSenderId: '60824383146',
    projectId: 'my-sports-calendar',
    storageBucket: 'my-sports-calendar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMYq7r1GqgDmTUG20PcozvVvhzNA0Pzk4',
    appId: '1:60824383146:ios:5ccfe678b0187e8825ead3',
    messagingSenderId: '60824383146',
    projectId: 'my-sports-calendar',
    storageBucket: 'my-sports-calendar.firebasestorage.app',
    androidClientId: '60824383146-3s4av4sabglb1tqp49nqgu26soqqqngb.apps.googleusercontent.com',
    iosClientId: '60824383146-g6h9as6s1tspd3646cl9q0lnfblk5qqv.apps.googleusercontent.com',
    iosBundleId: 'com.epin.mySportsCalendar',
  );

}